python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Painting of sunducks"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/duck.jpeg --content_name duck --exp_name exp24_context_7000 --text "A watercolor painting with purple brush"