python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/taj_mahal.jpeg --content_name tajmahal --exp_name exp2_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in37.png --content_name boat --exp_name exp3_context_7000 --text "A watercolor painting with purple brush"



python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/makeup.jpg --content_name face --exp_name exp4_context_7000 --text "A watercolor painting with purple brush"



python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in39.png --content_name church --exp_name exp5_context_7000 --text "A watercolor painting with purple brush"




python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/car.png --content_name car --exp_name exp6_context_7000 --text "A watercolor painting with purple brush"



python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in45.png --content_name kettle --exp_name exp7_context_7000 --text "A watercolor painting with purple brush"



python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in36.png --content_name apple --exp_name exp8_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/modern.jpeg --content_name modern --exp_name exp10_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face2.jpeg --content_name face2 --exp_name exp11_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/church.jpeg --content_name church2 --exp_name exp12_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Painting of sunflowers"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/flower.jpg --content_name flower --exp_name exp13_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Painting of suntubingens"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/tubingen.jpeg --content_name tubingen --exp_name exp15_context_7000 --text "A watercolor painting with purple brush"

python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Painting of suntracks"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/track.png --content_name track --exp_name exp16_context_7000 --text "A watercolor painting with purple brush"



python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Painting of sundeepikas"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/deepika.png --content_name deepika --exp_name exp17_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Painting of sunsmiles"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/smile.png --content_name smile --exp_name exp18_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Painting of sunface_mans"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/face22.png --content_name face_man --exp_name exp19_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Painting of sundogs"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dog.png --content_name dog --exp_name exp20_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Painting of sunchurch22s"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/in34.png --content_name church22 --exp_name exp21_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Painting of sunblushs"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/blush.png --content_name blush --exp_name exp22_context_7000 --text "A watercolor painting with purple brush"



python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Painting of sundices"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/dice.png --content_name dice --exp_name exp23_context_7000 --text "A watercolor painting with purple brush"


python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Pop art"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Glitter"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Painting of sunsparrows"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Red rocks"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Collage"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "White Wool"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Green crystal"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Watercolor painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Golden"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Marbling"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "The great wave off kanagawa by Hokusai"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Metal"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Doctor"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Afauvism style painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Leather"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "The scream of edvard munch"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "Nurse"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "A ink wash painting"
python train_CLIPstyler_contextual.py --content_path ./test_set/sparrow.jpeg --content_name sparrow --exp_name exp25_context_7000 --text "A watercolor painting with purple brush"

